proof system problem
discrete-math-ch/discmath pull request #95
Opened 2024-12-03 08:33 UTC by Tobotis

2024-12-03 08:39 UTC, M1ngXU commented
normalerweise schreiben wir das powerset mit $\mathcal P$, ist hier aber bisschen ambiguous 🫠 

und ist deine proof verification funktion nicht "computationally infeasible", also wenn S zu gross ist? Je nachdem wie sigma gegeben ist, wuerde ich P_2 = S x P_1 setzen, dann muss man immer das statement dazugeben welches wahr ist (und membership tests sind normalerweise schnell).

2024-12-03 08:40 UTC, M1ngXU requested changes

2024-12-03 08:40 UTC, M1ngXU commented on pages/content/ch6/proof-systems.mdx
> +        be a proof system which is sound and complete. Now define $\phi_2$ and $\mathcal{P}_2$ such that the following proof system is sound and complete (and prove these properties):
Vllt newline vor dem "Now define ...", dann ist etwas klarer was die aufgabe ist

2024-12-03 09:35 UTC, M1ngXU approved these changes

2024-12-04 17:05 UTC, Tobotis commented
Aber die Verificationsfunktion muss computationally feasible in der groesse von $P(\mathcal{S})$ sein oder nicht? Wenn wir $\mathcal{S} \times \mathcal{P}_2$ als Beweise nehmen, dann hat muss man immernoch memebership testen, was im schlimmsten fall $O(|P(\mathcal{S})|$ ist oder nicht, es sei denn man macht irgendein Preprocessing auf $P(\mathcal{S})$. Jedenfalls glaub ich, dass es nicht die Komplexität von $\phi$ verändern würde oder?

2024-12-04 17:07 UTC, real-yfprojects commented
> Aber die Verificationsfunktion muss computationally feasible in der groesse von P ( S ) sein oder nicht? 

Nein, in der Größe $|s|$ bei der Berechnung von $\phi(s,p)$.

2024-12-04 18:32 UTC, real-yfprojects commented
Für endliche Mengen S funktioniert die Aufgabe, für andere gibt es Probleme.

2024-12-05 08:34 UTC, Tobotis commented
> > Aber die Verificationsfunktion muss computationally feasible in der groesse von P ( S ) sein oder nicht?
> 
> Nein, in der Größe | s | bei der Berechnung von ϕ ( s , p ) .

Aber für $\phi_2$ in |P(s)|? Dann funktioniert es doch?!

2024-12-05 08:49 UTC, merged

2024-12-05 10:22 UTC, real-yfprojects commented
> Aber für $\phi_2$ in |P(s)|. Dann funktioniert es doch?!

Es funktioniert, aber die Aussage ist trotzdem falsch. Die Berechnung von $\varphi_2$ muss in $|S|$ liegen. Beachte, die Großschreibweise.

2024-12-05 14:48 UTC, Tobotis commented
Beachte die Grossschreibweise von $s$ in deinem ersten Kommentar, den Unterschied von $\mathcal{S}$ und $S$, den Unterschied zwischen $\varphi$ und $\phi$, sowie die regionalen Unterschiede in der Nutzung von "ß".
Ich verstehe nicht warum $\varphi_2$ in $O(|\mathcal{S})$ liegen muss (in dem Proof system, in dem $\varphi_2$ definiert wird ist $P(\mathcal{S})$ die Menge von Statements, oder was meinst du? 🤓

2024-12-06 18:47 UTC, real-yfprojects commented
> normalerweise schreiben wir das powerset mit P , ist hier aber bisschen ambiguous 🫠
> 
> und ist deine proof verification funktion nicht "computationally infeasible", also wenn S zu gross ist? Je nachdem wie sigma gegeben ist, wuerde ich P_2 = S x P_1 setzen, dann muss man immer das statement dazugeben welches wahr ist (und membership tests sind normalerweise schnell).

Habe gerade gelernt, das S und P rekursiv und effizient berechenbar sein müssen. Daher würde die Aufgabe mit dieser Lösung auch für unendliche Mengen S funktionieren.